spring:
  application:
    name: foobar-kata
server:
  port: 7003
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs

foobar-int-file-processor-batch:
  scheduler: 0 */5 * * * *
  input.file.path: src/main/resources/input.txt
  output.file.path: src/main/resources/result/output.txt
  chunk-size: 10



